# Generated by Django 4.2.24 on 2025-10-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("frontend_technologies", models.JSONField(blank=True, default=list)),
                ("backend_technologies", models.JSONField(blank=True, default=list)),
                ("other_technologies", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
